"""Create Voyager's planet, atmosphere, terrain, architecture and animal materials.

Run inside Unreal Editor 5.8 with -ExecutePythonScript=<this file>.
Terrain uses an original AI-generated albedo with seamless triplanar projection;
the other material patterns are generated by shader nodes. Re-running refreshes
only the named generated assets and preserves the original source PNG.
"""

import json
import hashlib
from pathlib import Path
import struct
import traceback


ROOT = Path(__file__).resolve().parents[1]
REPORT_PATH = ROOT / "Saved" / "VoyagerMaterialsReport.json"
ASSET_DIRECTORY = "/Game/Materials"
GROUND_SOURCE = ROOT / "Art" / "Textures" / "voyager_ground_albedo.png"
GROUND_ASSET = "/Game/Textures/T_VoyagerGround"
REQUIRED_ASSETS = [ASSET_DIRECTORY + "/M_VoyagerPlanet",
                   ASSET_DIRECTORY + "/M_VoyagerAtmosphere",
                   ASSET_DIRECTORY + "/M_VoyagerTerrain",
                   ASSET_DIRECTORY + "/M_VoyagerArchitecture",
                   ASSET_DIRECTORY + "/M_VoyagerAnimal", GROUND_ASSET]


def build_materials():
    import unreal

    assets = unreal.get_editor_subsystem(unreal.EditorAssetSubsystem)
    asset_tools = unreal.AssetToolsHelpers.get_asset_tools()
    editing = unreal.MaterialEditingLibrary
    results = []

    def log(message):
        unreal.log("VOYAGER MATERIALS: " + message)

    def expression(material, cls, x, y, **properties):
        node = editing.create_material_expression(material, cls, x, y)
        if node is None:
            raise RuntimeError("Could not create expression " + str(cls))
        for name, value in properties.items():
            node.set_editor_property(name, value)
        return node

    def link(source, destination, input_name):
        if not editing.connect_material_expressions(source, "", destination, input_name):
            raise RuntimeError("Could not connect " + source.get_name() + " to " +
                               destination.get_name() + "." + input_name)

    def output(source, property_name):
        if not editing.connect_material_property(source, "", property_name):
            raise RuntimeError("Could not connect material output " + str(property_name))

    def unary(mat, cls, source, pin="", **properties):
        node = expression(mat, cls, 0, 0, **properties)
        link(source, node, pin)
        return node

    def binary(mat, cls, first, second=None, **properties):
        node = expression(mat, cls, 0, 0, **properties)
        link(first, node, "A")
        if second is not None:
            link(second, node, "B")
        return node

    def mask(mat, source, channels):
        return unary(mat, unreal.MaterialExpressionComponentMask, source,
                     r="r" in channels, g="g" in channels, b="b" in channels, a=False)

    def scale(mat, source, factor):
        return binary(mat, unreal.MaterialExpressionMultiply, source, const_b=factor)

    def add(mat, source, value):
        return binary(mat, unreal.MaterialExpressionAdd, source, const_b=value)

    def constant_vector(mat, rgb):
        return expression(mat, unreal.MaterialExpressionConstant3Vector, 0, 0,
                          constant=unreal.LinearColor(*rgb, 0))

    def vector_parameter(mat, name, rgb):
        return expression(mat, unreal.MaterialExpressionVectorParameter, 0, 0,
                          parameter_name=name, default_value=unreal.LinearColor(*rgb, 1))

    def scalar_parameter(mat, name, value):
        return expression(mat, unreal.MaterialExpressionScalarParameter, 0, 0,
                          parameter_name=name, default_value=value)

    def blend(mat, first, second, alpha):
        node = expression(mat, unreal.MaterialExpressionLinearInterpolate, 0, 0)
        link(first, node, "A")
        link(second, node, "B")
        link(alpha, node, "Alpha")
        return node

    def ramp(mat, source, low, high):
        return unary(mat, unreal.MaterialExpressionSmoothStep, source, "Value",
                     const_min=low, const_max=high)

    def one_minus(mat, source):
        return unary(mat, unreal.MaterialExpressionOneMinus, source)

    def luminance(mat, source):
        return binary(mat, unreal.MaterialExpressionDotProduct, source,
                      constant_vector(mat, (.2126, .7152, .0722)))

    def triplanar(mat, coordinates, texture):
        normal = expression(mat, unreal.MaterialExpressionVertexNormalWS, 0, 0)
        normal_abs = unary(mat, unreal.MaterialExpressionAbs, normal)
        sharp_weights = unary(mat, unreal.MaterialExpressionPower, normal_abs, "Base", const_exponent=4.0)
        weight_sum = binary(mat, unreal.MaterialExpressionDotProduct, sharp_weights,
                            constant_vector(mat, (1, 1, 1)))
        weights = binary(mat, unreal.MaterialExpressionDivide, sharp_weights, weight_sum)
        weighted_samples = []
        for plane, component in (("gb", "r"), ("rb", "g"), ("rg", "b")):
            uv = mask(mat, coordinates, plane)
            sample = expression(mat, unreal.MaterialExpressionTextureSample, 0, 0,
                                texture=texture,
                                sampler_type=unreal.MaterialSamplerType.SAMPLERTYPE_COLOR,
                                sampler_source=unreal.SamplerSourceMode.SSM_WRAP_WORLD_GROUP_SETTINGS)
            link(uv, sample, "")
            weighted_samples.append(binary(mat, unreal.MaterialExpressionMultiply, sample,
                                           mask(mat, weights, component)))
        combined = binary(mat, unreal.MaterialExpressionAdd, weighted_samples[0], weighted_samples[1])
        return binary(mat, unreal.MaterialExpressionAdd, combined, weighted_samples[2])

    def import_ground_texture():
        source_info = {"path": GROUND_ASSET, "source": str(GROUND_SOURCE),
                       "provenance": "Original OpenAI image generation for Voyager; see Art/Textures/PROVENANCE.md"}
        if GROUND_SOURCE.is_file():
            data = GROUND_SOURCE.read_bytes()
            if len(data) < 24 or data[:8] != b"\x89PNG\r\n\x1a\n":
                raise RuntimeError("Ground albedo source is not a valid PNG: " + str(GROUND_SOURCE))
            source_info["source_size"] = list(struct.unpack(">II", data[16:24]))
            source_info["source_sha256"] = hashlib.sha256(data).hexdigest()
            task = unreal.AssetImportTask()
            for name, value in {"filename": str(GROUND_SOURCE), "destination_path": "/Game/Textures",
                                "destination_name": "T_VoyagerGround", "automated": True,
                                "replace_existing": True, "save": True,
                                "factory": unreal.TextureFactory()}.items():
                task.set_editor_property(name, value)
            asset_tools.import_asset_tasks([task])
            imported = list(task.get_editor_property("imported_object_paths"))
            if not imported:
                raise RuntimeError("Ground texture import returned no asset: " + str(GROUND_SOURCE))
            source_info["imported_objects"] = [str(path) for path in imported]
        elif not assets.does_asset_exist(GROUND_ASSET):
            raise RuntimeError("Missing generated albedo: " + str(GROUND_SOURCE))
        texture = assets.load_asset(GROUND_ASSET)
        if texture is None or not isinstance(texture, unreal.Texture2D):
            raise RuntimeError("Ground import did not produce a Texture2D at " + GROUND_ASSET)
        for name, value in {
            "srgb": True,
            "compression_settings": unreal.TextureCompressionSettings.TC_DEFAULT,
            "lod_group": unreal.TextureGroup.TEXTUREGROUP_WORLD,
            "mip_gen_settings": unreal.TextureMipGenSettings.TMGS_FROM_TEXTURE_GROUP,
            "address_x": unreal.TextureAddress.TA_WRAP,
            "address_y": unreal.TextureAddress.TA_WRAP,
            # The original is1254px. Stretching (not padding) maintains wrapping
            # edges while enabling a full2048px power-of-two mip chain.
            "power_of_two_mode": unreal.TexturePowerOfTwoSetting.STRETCH_TO_POWER_OF_TWO,
            "max_texture_size": 2048,
            "never_stream": False,
        }.items():
            texture.set_editor_property(name, value)
        if not assets.save_loaded_asset(texture, False):
            raise RuntimeError("Could not save imported ground texture")
        if not assets.does_asset_exist(GROUND_ASSET):
            raise RuntimeError("Ground texture disappeared after saving")
        source_info["mipmaps"] = "TextureGroup World; power-of-two stretch; maximum2048px"
        source_info["addressing"] = "wrap U/V"
        log("SAVED T_VoyagerGround / original albedo / wrap / generated mipmaps")
        return texture, source_info

    def material(name, shading_model, blend_mode):
        path = ASSET_DIRECTORY + "/" + name
        value = assets.load_asset(path) if assets.does_asset_exist(path) else None
        if value is None:
            value = asset_tools.create_asset(name, ASSET_DIRECTORY, unreal.Material,
                                             unreal.MaterialFactoryNew())
        if value is None or not isinstance(value, unreal.Material):
            raise RuntimeError("Expected a Material asset at " + path)
        editing.delete_all_material_expressions(value)
        value.set_editor_property("shading_model", shading_model)
        value.set_editor_property("blend_mode", blend_mode)
        value.set_editor_property("two_sided", False)
        editing.set_base_material_usage(value, unreal.MaterialUsage.MATUSAGE_INSTANCED_STATIC_MESHES, True)
        return value

    def save_material(value, parameters):
        editing.layout_material_expressions(value)
        # UE 5.8's MaterialEditingLibrary.h specifies a returned TArray<FString>
        # of compiler errors. Older versions can return None instead.
        compilation_result = editing.recompile_material(value)
        if compilation_result:
            if isinstance(compilation_result, str):
                errors = [compilation_result]
            else:
                errors = [str(error) for error in compilation_result]
            raise RuntimeError("Shader compilation failed for " + value.get_name() +
                               ": " + "; ".join(errors))
        if not assets.save_loaded_asset(value, False):
            raise RuntimeError("Could not save " + value.get_path_name())
        if not assets.does_asset_exist(value.get_path_name()):
            raise RuntimeError("Saved material is missing: " + value.get_path_name())
        count = editing.get_num_material_expressions(value)
        if count < 4:
            raise RuntimeError("Material graph unexpectedly empty: " + value.get_name())
        entry = {"path": value.get_path_name(), "expressions": count,
                 "parameters": parameters, "compiler_errors": [],
                 "compiler_validation": "returned errors checked" if compilation_result is not None
                 else "recompile API does not expose errors"}
        results.append(entry)
        log("SAVED " + value.get_name() + " / " + str(count) + " expressions / shader compile passed")

    ground_texture, texture_report = import_ground_texture()

    log("BUILD M_VoyagerPlanet / normalized spherical continents and cloud veil")
    planet = material("M_VoyagerPlanet", unreal.MaterialShadingModel.MSM_DEFAULT_LIT,
                      unreal.BlendMode.BLEND_OPAQUE)
    world = expression(planet, unreal.MaterialExpressionWorldPosition, -1800, 0,
                       desc="Absolute pixel world position")
    center = expression(planet, unreal.MaterialExpressionObjectPositionWS, -1800, 170,
                        desc="Planet bounds center")
    radius = expression(planet, unreal.MaterialExpressionObjectRadius, -1550, 310,
                        desc="World-space radius keeps detail stable on every planet size")
    relative = expression(planet, unreal.MaterialExpressionSubtract, -1520, 0)
    link(world, relative, "A")
    link(center, relative, "B")
    normalized = expression(planet, unreal.MaterialExpressionDivide, -1290, 0,
                            desc="Object-centered spherical coordinates: (World - Center) / Radius")
    link(relative, normalized, "A")
    link(radius, normalized, "B")

    # Each orbital position receives its own stable noise slice. SeedOffset can
    # further vary coastlines between generated star systems at the same orbit.
    position_seed = expression(planet, unreal.MaterialExpressionMultiply, -1510, 500,
                               const_b=0.000137, desc="Stable per-orbit pattern offset")
    link(center, position_seed, "A")
    seed_offset = expression(planet, unreal.MaterialExpressionVectorParameter, -1500, 680,
                             parameter_name="SeedOffset", default_value=unreal.LinearColor(0, 0, 0, 0),
                             desc="Optional deterministic seed offset for runtime planet instances")
    all_offsets = expression(planet, unreal.MaterialExpressionAdd, -1250, 450)
    link(position_seed, all_offsets, "A")
    link(seed_offset, all_offsets, "B")
    coordinates = expression(planet, unreal.MaterialExpressionAdd, -1010, 0)
    link(normalized, coordinates, "A")
    link(all_offsets, coordinates, "B")

    continents = expression(planet, unreal.MaterialExpressionNoise, -750, 0,
                            noise_function=unreal.NoiseFunction.NOISEFUNCTION_GRADIENT_TEX3D,
                            scale=5.0, levels=3, quality=1, level_scale=2.0,
                            output_min=0.0, output_max=1.0, turbulence=False,
                            desc="Three inexpensive 3D-texture octaves shape islands and continental shelves")
    # In 5.8 the first pin's display name changes with its position origin.
    link(coordinates, continents, "")
    coastline = expression(planet, unreal.MaterialExpressionSmoothStep, -500, 0,
                           const_min=0.45, const_max=0.55,
                           desc="Soft but distinct coastline threshold")
    link(continents, coastline, "Value")
    ocean = expression(planet, unreal.MaterialExpressionVectorParameter, -750, -420,
                       parameter_name="Tint", default_value=unreal.LinearColor(0.018, 0.075, 0.19, 1),
                       desc="Runtime ocean color")
    land = expression(planet, unreal.MaterialExpressionVectorParameter, -750, -240,
                      parameter_name="LandTint", default_value=unreal.LinearColor(0.22, 0.42, 0.18, 1),
                      desc="Runtime continent color")
    land_and_sea = expression(planet, unreal.MaterialExpressionLinearInterpolate, -250, -180)
    link(ocean, land_and_sea, "A")
    link(land, land_and_sea, "B")
    link(coastline, land_and_sea, "Alpha")

    cloud_offset = expression(planet, unreal.MaterialExpressionConstant3Vector, -1020, 520,
                              constant=unreal.LinearColor(1.73, 8.31, -2.47, 0))
    cloud_coordinates = expression(planet, unreal.MaterialExpressionAdd, -770, 430)
    link(coordinates, cloud_coordinates, "A")
    link(cloud_offset, cloud_coordinates, "B")
    cloud_noise = expression(planet, unreal.MaterialExpressionNoise, -530, 410,
                             noise_function=unreal.NoiseFunction.NOISEFUNCTION_GRADIENT_TEX3D,
                             scale=13.0, levels=2, quality=1, level_scale=2.1,
                             output_min=0.0, output_max=1.0, turbulence=False,
                             desc="Independent higher-frequency cloud wisps")
    link(cloud_coordinates, cloud_noise, "")
    cloud_mask = expression(planet, unreal.MaterialExpressionSmoothStep, -290, 410,
                            const_min=0.70, const_max=0.85,
                            desc="Sparse cloud banks preserve the planet colors below")
    link(cloud_noise, cloud_mask, "Value")
    cloud_strength = expression(planet, unreal.MaterialExpressionMultiply, -50, 400, const_b=0.35)
    link(cloud_mask, cloud_strength, "A")
    cloud_white = expression(planet, unreal.MaterialExpressionConstant3Vector, -40, 180,
                             constant=unreal.LinearColor(0.78, 0.84, 0.88, 1))
    final_color = expression(planet, unreal.MaterialExpressionLinearInterpolate, 220, -110,
                             desc="A restrained cloud veil over continuous smooth geometry")
    link(land_and_sea, final_color, "A")
    link(cloud_white, final_color, "B")
    link(cloud_strength, final_color, "Alpha")
    output(final_color, unreal.MaterialProperty.MP_BASE_COLOR)

    roughness = expression(planet, unreal.MaterialExpressionConstant, 240, 350, r=0.9)
    specular = expression(planet, unreal.MaterialExpressionConstant, 240, 470, r=0.1)
    output(roughness, unreal.MaterialProperty.MP_ROUGHNESS)
    output(specular, unreal.MaterialProperty.MP_SPECULAR)
    rim = expression(planet, unreal.MaterialExpressionFresnel, -510, 850,
                     exponent=5.0, base_reflect_fraction=0.0)
    colored_rim = expression(planet, unreal.MaterialExpressionMultiply, -260, 830)
    link(rim, colored_rim, "A")
    link(ocean, colored_rim, "B")
    faint_rim = expression(planet, unreal.MaterialExpressionMultiply, 10, 810, const_b=0.12)
    link(colored_rim, faint_rim, "A")
    output(faint_rim, unreal.MaterialProperty.MP_EMISSIVE_COLOR)
    save_material(planet, ["Tint", "LandTint", "SeedOffset"])

    log("BUILD M_VoyagerAtmosphere / additive Fresnel sphere shell")
    atmosphere = material("M_VoyagerAtmosphere", unreal.MaterialShadingModel.MSM_UNLIT,
                          unreal.BlendMode.BLEND_ADDITIVE)
    atmosphere_tint = expression(atmosphere, unreal.MaterialExpressionVectorParameter, -650, -120,
                                 parameter_name="Tint", default_value=unreal.LinearColor(0.12, 0.38, 0.90, 1),
                                 desc="Runtime atmosphere color; use on a slightly larger sphere shell")
    fresnel = expression(atmosphere, unreal.MaterialExpressionFresnel, -650, 180,
                         exponent=5.0, base_reflect_fraction=0.0,
                         desc="Zero face-on opacity; light collects at the planet horizon")
    emission = expression(atmosphere, unreal.MaterialExpressionMultiply, -320, -120, const_b=0.6)
    link(atmosphere_tint, emission, "A")
    opacity = expression(atmosphere, unreal.MaterialExpressionMultiply, -320, 180, const_b=0.3)
    link(fresnel, opacity, "A")
    output(emission, unreal.MaterialProperty.MP_EMISSIVE_COLOR)
    output(opacity, unreal.MaterialProperty.MP_OPACITY)
    save_material(atmosphere, ["Tint"])

    log("BUILD M_VoyagerTerrain / shared planetary coordinates and seamless surface detail")
    terrain = material("M_VoyagerTerrain", unreal.MaterialShadingModel.MSM_DEFAULT_LIT,
                       unreal.BlendMode.BLEND_OPAQUE)
    terrain_world = expression(terrain, unreal.MaterialExpressionWorldPosition, -1600, 0,
                               desc="Absolute world position shared across every terrain patch")
    terrain_center = expression(terrain, unreal.MaterialExpressionVectorParameter, -1600, 170,
                                parameter_name="PlanetCenter", default_value=unreal.LinearColor(0, 0, -60000000, 0),
                                desc="Runtime planet center in world centimetres; never patch object bounds")
    terrain_radius = expression(terrain, unreal.MaterialExpressionScalarParameter, -1350, 320,
                                parameter_name="PlanetRadius", default_value=60000000.0,
                                desc="Runtime reference radius in centimetres")
    terrain_relative = expression(terrain, unreal.MaterialExpressionSubtract, -1350, 0)
    link(terrain_world, terrain_relative, "A")
    link(terrain_center, terrain_relative, "B")
    terrain_normalized = expression(terrain, unreal.MaterialExpressionDivide, -1110, 0,
                                    desc="One spherical coordinate field for near patches and distant terrain")
    link(terrain_relative, terrain_normalized, "A")
    link(terrain_radius, terrain_normalized, "B")
    terrain_seed = expression(terrain, unreal.MaterialExpressionVectorParameter, -1110, 190,
                              parameter_name="SeedOffset", default_value=unreal.LinearColor(0, 0, 0, 0))
    terrain_coordinates = expression(terrain, unreal.MaterialExpressionAdd, -870, 0)
    link(terrain_normalized, terrain_coordinates, "A")
    link(terrain_seed, terrain_coordinates, "B")
    macro_noise = expression(terrain, unreal.MaterialExpressionNoise, -620, 0,
                             noise_function=unreal.NoiseFunction.NOISEFUNCTION_GRADIENT_TEX3D,
                             scale=4.7, levels=2, quality=1, level_scale=2.1,
                             output_min=0.25, output_max=0.65, turbulence=False,
                             desc="Two cheap octaves provide gentle continuous continental color variation")
    link(terrain_coordinates, macro_noise, "")
    terrain_tint = expression(terrain, unreal.MaterialExpressionVectorParameter, -620, -420,
                              parameter_name="Tint", default_value=unreal.LinearColor(.10, .20, .12, 1),
                              desc="Base ground color")
    terrain_land = expression(terrain, unreal.MaterialExpressionVectorParameter, -620, -230,
                              parameter_name="LandTint", default_value=unreal.LinearColor(.18, .28, .15, 1),
                              desc="Secondary soil and rock tone")
    macro_color = expression(terrain, unreal.MaterialExpressionLinearInterpolate, -370, -140)
    link(terrain_tint, macro_color, "A")
    link(terrain_land, macro_color, "B")
    link(macro_noise, macro_color, "Alpha")

    # Light polar mineral/snow variation stays subordinate to the runtime biome.
    # SnowCoverage can be zero on volcanic worlds or raised for frozen biomes.
    latitude = unary(terrain, unreal.MaterialExpressionAbs, mask(terrain, terrain_normalized, "b"))
    snow_mask = binary(terrain, unreal.MaterialExpressionMultiply, ramp(terrain, latitude, .965, .995),
                       scalar_parameter(terrain, "SnowCoverage", .10))
    macro_color = blend(terrain, macro_color,
                        vector_parameter(terrain, "SnowTint", (.74, .79, .82)), snow_mask)

    # Keep fine coordinates small on distant worlds. Each unrotated, unit-scale
    # patch supplies frac((patch origin - planet center) /400cm) in primitive
    # data slots 0..2. Local position preserves centimetre precision; that fixed
    # fractional offset keeps all three wrapped projections continuous between
    # patches without adding enormous planet-relative positions in the shader.
    patch_position = unary(terrain, unreal.MaterialExpressionTransformPosition, terrain_world,
                           transform_source_type=unreal.MaterialPositionTransformSource.TRANSFORMPOSSOURCE_WORLD,
                           transform_type=unreal.MaterialPositionTransformSource.TRANSFORMPOSSOURCE_LOCAL)
    patch_coordinates = binary(terrain, unreal.MaterialExpressionDivide, patch_position, const_b=400.0)
    detail_origin_fraction = expression(terrain, unreal.MaterialExpressionVectorParameter, 0, 0,
                                        parameter_name="DetailOriginFraction",
                                        default_value=unreal.LinearColor(0, 0, 0, 0),
                                        use_custom_primitive_data=True, primitive_data_index=0,
                                        desc="Primitive data 0..2: frac((patch origin - planet center) /400cm). Fixed 4m texture tile.")
    texture_coordinates = binary(terrain, unreal.MaterialExpressionAdd, patch_coordinates, detail_origin_fraction)
    grain = triplanar(terrain, texture_coordinates, ground_texture)
    texture_modulation = add(terrain, scale(terrain, grain, .90), .55)
    detailed_color = expression(terrain, unreal.MaterialExpressionMultiply, -100, 40)
    link(macro_color, detailed_color, "A")
    link(texture_modulation, detailed_color, "B")

    # Suppress subpixel grain from orbit. This costs no additional noise octave
    # and keeps the same continuous macro color on all terrain LODs.
    pixel_depth = expression(terrain, unreal.MaterialExpressionPixelDepth, -610, 660)
    detail_distance = expression(terrain, unreal.MaterialExpressionDivide, -370, 660, const_b=60000.0)
    link(pixel_depth, detail_distance, "A")
    detail_clamp = expression(terrain, unreal.MaterialExpressionClamp, -120, 650,
                              min_default=0.0, max_default=1.0)
    link(detail_distance, detail_clamp, "")
    detail_fade = expression(terrain, unreal.MaterialExpressionOneMinus, 120, 620)
    link(detail_clamp, detail_fade, "")
    terrain_final = expression(terrain, unreal.MaterialExpressionLinearInterpolate, 380, -80,
                               desc="Surface grain fades smoothly over the first 600 metres of view distance")
    link(macro_color, terrain_final, "A")
    link(detailed_color, terrain_final, "B")
    link(detail_fade, terrain_final, "Alpha")
    output(terrain_final, unreal.MaterialProperty.MP_BASE_COLOR)
    surface_luminance = luminance(terrain, grain)
    varied_roughness = add(terrain, scale(terrain, one_minus(terrain, surface_luminance), .18), .78)
    terrain_roughness = blend(terrain,
                             expression(terrain, unreal.MaterialExpressionConstant, 370, 170, r=.92),
                             varied_roughness, detail_fade)
    terrain_specular = expression(terrain, unreal.MaterialExpressionConstant, 370, 300, r=.12)
    output(terrain_roughness, unreal.MaterialProperty.MP_ROUGHNESS)
    output(terrain_specular, unreal.MaterialProperty.MP_SPECULAR)

    # Epic's shipped surface-gradient function differentiates the sampled bump
    # in screen space: it needs no extra texture reads and returns a WS normal.
    perturb_asset = assets.load_asset("/Engine/Functions/Engine_MaterialFunctions03/Procedurals/PerturbNormalLQ")
    if perturb_asset is None:
        raise RuntimeError("Installed engine lacks the PerturbNormalLQ material function")
    bump = binary(terrain, unreal.MaterialExpressionMultiply, surface_luminance,
                  scalar_parameter(terrain, "BumpStrength", 4.0))
    bump = binary(terrain, unreal.MaterialExpressionMultiply, bump, detail_fade)
    perturb = expression(terrain, unreal.MaterialExpressionMaterialFunctionCall, 620, 330,
                         material_function=perturb_asset)
    link(bump, perturb, "Bump")
    terrain.set_editor_property("tangent_space_normal", False)
    output(perturb, unreal.MaterialProperty.MP_NORMAL)
    save_material(terrain, ["PlanetCenter", "PlanetRadius", "SeedOffset", "Tint", "LandTint",
                            "DetailOriginFraction", "BumpStrength", "SnowCoverage", "SnowTint"])

    log("BUILD M_VoyagerArchitecture / metal facade panels and varied lit windows")
    architecture = material("M_VoyagerArchitecture", unreal.MaterialShadingModel.MSM_DEFAULT_LIT,
                            unreal.BlendMode.BLEND_OPAQUE)
    building_world = expression(architecture, unreal.MaterialExpressionWorldPosition, 0, 0)
    building_local = unary(architecture, unreal.MaterialExpressionTransformPosition, building_world,
                           transform_source_type=unreal.MaterialPositionTransformSource.TRANSFORMPOSSOURCE_WORLD,
                           transform_type=unreal.MaterialPositionTransformSource.TRANSFORMPOSSOURCE_INSTANCE)
    building_normal = unary(architecture, unreal.MaterialExpressionTransform,
                            expression(architecture, unreal.MaterialExpressionVertexNormalWS, 0, 0),
                            transform_source_type=unreal.MaterialVectorCoordTransformSource.TRANSFORMSOURCE_WORLD,
                            transform_type=unreal.MaterialVectorCoordTransform.TRANSFORM_INSTANCE)
    building_normal = unary(architecture, unreal.MaterialExpressionNormalize, building_normal)
    side_mask = one_minus(architecture, ramp(architecture,
                         unary(architecture, unreal.MaterialExpressionAbs, mask(architecture, building_normal, "b")), .65, .90))
    panel_coords = binary(architecture, unreal.MaterialExpressionDivide, building_local,
                          scalar_parameter(architecture, "PanelSize", 14.0))
    horizontal = binary(architecture, unreal.MaterialExpressionAdd,
                        mask(architecture, panel_coords, "r"), mask(architecture, panel_coords, "g"))
    vertical = mask(architecture, panel_coords, "b")
    fraction_x = unary(architecture, unreal.MaterialExpressionFrac, horizontal)
    fraction_y = unary(architecture, unreal.MaterialExpressionFrac, vertical)

    window_x = binary(architecture, unreal.MaterialExpressionMultiply,
                      ramp(architecture, fraction_x, .16, .20),
                      one_minus(architecture, ramp(architecture, fraction_x, .79, .83)))
    window_y = binary(architecture, unreal.MaterialExpressionMultiply,
                      ramp(architecture, fraction_y, .24, .28),
                      one_minus(architecture, ramp(architecture, fraction_y, .72, .76)))
    windows = binary(architecture, unreal.MaterialExpressionMultiply, window_x, window_y)
    windows = binary(architecture, unreal.MaterialExpressionMultiply, windows, side_mask)
    seam_x = one_minus(architecture, ramp(architecture, fraction_x, .015, .035))
    seam_y = one_minus(architecture, ramp(architecture, fraction_y, .015, .035))
    seams = unary(architecture, unreal.MaterialExpressionClamp,
                  binary(architecture, unreal.MaterialExpressionAdd, seam_x, seam_y),
                  min_default=0.0, max_default=1.0)
    building_tint = vector_parameter(architecture, "Tint", (.19, .24, .28))
    facade_color = blend(architecture, building_tint, scale(architecture, building_tint, .38), seams)
    window_tint = vector_parameter(architecture, "WindowTint", (.31, .61, .85))
    building_color = blend(architecture, facade_color, scale(architecture, window_tint, .09), windows)
    output(building_color, unreal.MaterialProperty.MP_BASE_COLOR)

    # A cheap deterministic hash lights different rooms. No texture or 3D noise
    # is needed for architecture, and the grid follows each building instance.
    cell_x = unary(architecture, unreal.MaterialExpressionFloor, horizontal)
    cell_y = unary(architecture, unreal.MaterialExpressionFloor, vertical)
    room_hash = binary(architecture, unreal.MaterialExpressionAdd,
                       scale(architecture, cell_x, 12.9898), scale(architecture, cell_y, 78.233))
    room_hash = unary(architecture, unreal.MaterialExpressionSine, room_hash, period=1.0)
    room_hash = unary(architecture, unreal.MaterialExpressionFrac, scale(architecture, room_hash, 43758.5453))
    lit_windows = binary(architecture, unreal.MaterialExpressionMultiply, windows,
                         ramp(architecture, room_hash, .42, .50))
    emission_windows = binary(architecture, unreal.MaterialExpressionMultiply, lit_windows,
                              scalar_parameter(architecture, "WindowGlow", 2.4))
    emission_windows = binary(architecture, unreal.MaterialExpressionMultiply, emission_windows, window_tint)
    output(emission_windows, unreal.MaterialProperty.MP_EMISSIVE_COLOR)
    glass_roughness = expression(architecture, unreal.MaterialExpressionConstant, 0, 0, r=.24)
    output(blend(architecture, scalar_parameter(architecture, "Roughness", .68), glass_roughness, windows),
           unreal.MaterialProperty.MP_ROUGHNESS)
    metal_mask = one_minus(architecture, scale(architecture, windows, .80))
    output(binary(architecture, unreal.MaterialExpressionMultiply, metal_mask,
                  scalar_parameter(architecture, "Metallic", .42)), unreal.MaterialProperty.MP_METALLIC)
    output(expression(architecture, unreal.MaterialExpressionConstant, 0, 0, r=.35),
           unreal.MaterialProperty.MP_SPECULAR)
    save_material(architecture, ["Tint", "PanelSize", "WindowTint", "WindowGlow", "Roughness", "Metallic"])

    log("BUILD M_VoyagerAnimal / local coat grain and restrained stripes")
    animal = material("M_VoyagerAnimal", unreal.MaterialShadingModel.MSM_DEFAULT_LIT,
                      unreal.BlendMode.BLEND_OPAQUE)
    animal_world = expression(animal, unreal.MaterialExpressionWorldPosition, 0, 0)
    animal_local = unary(animal, unreal.MaterialExpressionTransformPosition, animal_world,
                         transform_source_type=unreal.MaterialPositionTransformSource.TRANSFORMPOSSOURCE_WORLD,
                         transform_type=unreal.MaterialPositionTransformSource.TRANSFORMPOSSOURCE_INSTANCE)
    coat_noise = unary(animal, unreal.MaterialExpressionNoise, animal_local,
                       noise_function=unreal.NoiseFunction.NOISEFUNCTION_GRADIENT_TEX3D,
                       scale=.65, levels=1, quality=1, level_scale=2.0,
                       output_min=.0, output_max=1.0, turbulence=False,
                       desc="One cheap coat-detail octave, fixed in each moving body part's local space")
    coat_tint = vector_parameter(animal, "Tint", (.31, .23, .15))
    coat_grain = add(animal, scale(animal, coat_noise, .20), .88)
    coat_color = binary(animal, unreal.MaterialExpressionMultiply, coat_tint, coat_grain)
    stripe_phase = binary(animal, unreal.MaterialExpressionMultiply, mask(animal, animal_local, "r"),
                          scalar_parameter(animal, "StripeScale", .075))
    stripe_phase = binary(animal, unreal.MaterialExpressionAdd, stripe_phase, scale(animal, coat_noise, .30))
    stripes = unary(animal, unreal.MaterialExpressionSine, stripe_phase, period=1.0)
    stripe_mask = binary(animal, unreal.MaterialExpressionMultiply, ramp(animal, stripes, .15, .62),
                         scalar_parameter(animal, "StripeStrength", .32))
    output(blend(animal, coat_color, scale(animal, coat_tint, .40), stripe_mask),
           unreal.MaterialProperty.MP_BASE_COLOR)
    output(add(animal, scale(animal, coat_noise, .06), .84), unreal.MaterialProperty.MP_ROUGHNESS)
    output(expression(animal, unreal.MaterialExpressionConstant, 0, 0, r=.18), unreal.MaterialProperty.MP_SPECULAR)
    save_material(animal, ["Tint", "StripeScale", "StripeStrength"])

    missing = [path for path in REQUIRED_ASSETS if not assets.does_asset_exist(path)]
    if missing:
        raise RuntimeError("Missing generated assets: " + ", ".join(missing))
    report = {"status": "success", "materials": results, "textures": [texture_report],
              "terrain_detail_mapping": {
                  "tile_size_cm": 400,
                  "primitive_parameter": "DetailOriginFraction",
                  "primitive_data_indices": [0, 1, 2],
                  "offset_formula": "frac((patch origin - planet center) /400cm)",
                  "requirements": "Unrotated terrain patches at unit scale; one shared material; no camera-dependent offset",
                  "other_meshes": "Zero custom data gives object-local texture coordinates"},
              "provenance": {
                  "ground_albedo": "Original AI-generated image created for this project; source and prompt in Art/Textures/PROVENANCE.md",
                  "material_graphs": "Original procedural graphs; no downloaded photography or third-party surface texture packs",
                  "bump_function": "PerturbNormalLQ from the installed Unreal Engine content library"}}
    REPORT_PATH.parent.mkdir(parents=True, exist_ok=True)
    REPORT_PATH.write_text(json.dumps(report, indent=2), encoding="utf-8")
    log("SUCCESS / five materials and one original albedo compiled, saved, and verified / " + str(REPORT_PATH))


def main():
    try:
        build_materials()
    except Exception:
        import unreal
        detail = traceback.format_exc()
        REPORT_PATH.parent.mkdir(parents=True, exist_ok=True)
        REPORT_PATH.write_text(json.dumps({"status": "failed", "error": detail}, indent=2), encoding="utf-8")
        unreal.log_error("VOYAGER MATERIALS FAILED:\n" + detail)
        raise


if __name__ == "__main__":
    main()
